- name: Apply Kubernetes manifests
  kubernetes.core.k8s:
    state: present
    src: "{{ item }}"
  loop:
    - "{{ playbook_dir }}/.rendered/backend-namespace.yaml"
    - "{{ playbook_dir }}/.rendered/backend-deployment.yaml"
    - "{{ playbook_dir }}/.rendered/backend-service.yaml"
    - "{{ playbook_dir }}/.rendered/backend-hpa.yaml"
    - "{{ playbook_dir }}/.rendered/backend-pdb.yaml"
    - "{{ playbook_dir }}/.rendered/backend-ingress.yaml"