apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: backend-servicemonitor
  namespace: test
  labels:
    release: prometheus         
spec:
  selector:
    matchLabels:
      app: backend
  namespaceSelector:
    matchNames: [ "test" ]
  endpoints:
    - port: metrics
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s