name: Deploy with Ansible

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Ansible and deps
        run: |
          python -m pip install --upgrade pip
          pip install "ansible>=8.0.0"
          ansible-galaxy collection install kubernetes.core

      - name: Validate cluster access
        run: |
          kubectl version --short
          kubectl get nodes

      - name: Deploy to dev
        run: |
          ansible-playbook -i ansible/inventories/dev/hosts.ini ansible/playbook.yaml
